[package]
name = "tetris"
version = "0.1.1"
authors = ["chunlinwang <chunlinwang1983@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.0"
conrod_core = "0.71.0"
conrod_glium = "0.71.0"
conrod_winit = "0.71.0"
find_folder = "0.3.0"
glium = "0.28.0"
image = "0.23.13"
winit = "0.23.0"

